name: End-to-end test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup-Python
        uses: actions/setup-python@v2.2.1
        with:
          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
          python-version: 3.8 # optional, default is 3.x
          
      - name: Setup-Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable

      # Runs a single command using the runners shell
      - name: Install-jq
        run: sudo apt-get install
        
      - name: Generate Rust binary
        run: cargo build --release --bin extract_comp

      # Runs a set of commands using the runners shell
      - name: Run script
        run: bash -x data/download-extract/download-extract.sh < data/results_example_gds.txt
