name: Build & Test

on:
  push:
    paths: [ examples/**, src/**, Cargo.toml, .github/workflows/test.yml ]
  pull_request:
    branches: [ master ]
    paths: [ examples/**, src/**, Cargo.toml, .github/workflows/test.yml ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check syntax correctness
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo check
  test:
    name: Run unit tests
    needs: check
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test
      
  run-plot-comp:
    name: Test plot-comp
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo run --example plot-comp

      - name: Compare ref outputs to program outputs
        run: diff examples/plot-comp/out.png examples/plot-comp/out-ref.png 
          
  run-extract-comp:
    name: Test extract-comp
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: cargo run --example extract-comp

      - name: Compare ref outputs to program outputs
        run: diff examples/extract-comp/out.json examples/extract-comp/out-ref.json
