name: Build & Test

on:
  push:
    paths: [ examples/**, src/**, Cargo.toml, .github/workflows/test.yml ]
  pull_request:
    branches: [ master ]
    paths: [ examples/**, src/**, Cargo.toml, .github/workflows/test.yml ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Check:
    name: Check syntax correctness
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        name: Cache Cargo Build Dependencies
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: cargo check
  Test:
    name: Run unit tests
    needs: check
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        name: Cache Cargo Build Dependencies
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: cargo test
          
  run-extract-comp:
    name: Test extract-comp
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/cache@v2
        name: Cache Cargo Build Dependencies
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: cargo run --example extract-comp

      - name: Compare ref outputs to program outputs
        run: diff examples/extract-comp/out.json examples/extract-comp/out-ref.json
